INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('ABW', 'Aruba');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('AFG', 'Afganistan');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('AGO', 'Angola');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('ALB', 'Albania');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('AND', 'Andorra');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('ARB', 'El Mundo Arabe');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('ARE', 'Emiratos Arabes Unidos');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('ARG', 'Argentina');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('ARM', 'Armenia');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('ASM', 'Samoa Americana');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('ATG', 'Antigua Y Barbuda');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('AUS', 'Australia');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('AUT', 'Austria');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('AZE', 'Azerbaiyan');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('BDI', 'Burundi');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('BEL', 'Belgica');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('BEN', 'Benin');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('BFA', 'Burkina Faso');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('BGD', 'Bangladesh');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('BGR', 'Bulgaria');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('BHR', 'Bahrein');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('BHS', 'Bahamas');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('BIH', 'Bosnia Y Herzegovina');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('BLR', 'Belarus');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('BLZ', 'Belice');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('BMU', 'Bermudas');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('BOL', 'Bolivia');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('BRA', 'Brasil');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('BRB', 'Barbados');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('BRN', 'Brunei Darussalam');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('BTN', 'Bhutan');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('BWA', 'Botswana');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('CAF', 'Republica Centroafricana');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('CAN', 'Canada');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('CEB', 'Europa Central Y Del Baltico');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('CHE', 'Suiza');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('CHI', 'Islas Del Canal');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('CHL', 'Chile');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('CHN', 'China');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('CIV', 'CÃ´te D''Ivoire');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('CMR', 'Camerun');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('COD', 'Congo, Republica Democratica Del');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('COG', 'Congo, Republica Del');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('COL', 'Colombia');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('COM', 'Comoras');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('CPV', 'Cabo Verde');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('CRI', 'Costa Rica');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('CSS', 'Estados Pequeos Del Caribe');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('CUB', 'Cuba');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('CUW', 'Curacao');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('CYM', 'Islas Caiman');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('CYP', 'Chipre');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('CZE', 'Republica Checa');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('DEU', 'Alemania');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('DJI', 'Djibouti');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('DMA', 'Dominica');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('DNK', 'Dinamarca');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('DOM', 'Republica Dominicana');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('DZA', 'Argelia');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('EAP', 'Asia Oriental Y El Pacifico (Excluido Altos Ingresos)');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('EAR', 'Inicial Del Dividendo Demografico');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('EAS', 'Asia Oriental Y El Pacifico');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('ECA', 'Europa Y Asia Central (Excluido Altos Ingresos)');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('ECS', 'Europa Y Asia Central');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('ECU', 'Ecuador');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('EGY', 'Egipto, Republica Arabe De');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('EMU', 'Zona Del Euro');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('ERI', 'Eritrea');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('ESP', 'EspaÃ±a');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('EST', 'Estonia');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('ETH', 'Etiopia');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('EUU', 'Union Europea');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('FCS', 'Fragiles Y Situaciones De Conflicto Afectados');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('FIN', 'Finlandia');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('FJI', 'Fiji');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('FRA', 'Francia');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('FRO', 'Islas Feroe');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('FSM', 'Micronesia (Estados Federados De)');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('GAB', 'Gabon');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('GBR', 'Reino Unido');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('GEO', 'Georgia');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('GHA', 'Ghana');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('GIB', 'Gibraltar');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('GIN', 'Guinea');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('GMB', 'Gambia');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('GNB', 'Guinea-Bissau');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('GNQ', 'Guinea Ecuatorial');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('GRC', 'Grecia');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('GRD', 'Granada');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('GRL', 'Groenlandia');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('GTM', 'Guatemala');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('GUM', 'Guam');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('GUY', 'Guyana');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('HIC', 'Ingreso Alto');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('HKG', 'Hong Kong, Region Administrativa Especial');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('HND', 'Honduras');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('HPC', 'Paises Pobres Muy Endeudados (Ppme)');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('HRV', 'Croacia');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('HTI', 'Haiti');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('HUN', 'Hungria');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('IBD', 'Solo Birf');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('IBT', 'Birf Y La Aif');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('IDA', 'Total De La Aif');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('IDB', 'Mezcla De La Aif');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('IDN', 'Indonesia');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('IDX', 'Solo Aif');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('IMN', 'Isla De Man');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('IND', 'India');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('INX', 'No Clasificado');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('IRL', 'Irlanda');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('IRN', 'Iran, Republica Islamica Del');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('IRQ', 'Iraq');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('ISL', 'Islandia');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('ISR', 'Israel');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('ITA', 'Italia');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('JAM', 'Jamaica');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('JOR', 'Jordania');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('JPN', 'Japon');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('KAZ', 'Kazajstan');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('KEN', 'Kenya');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('KGZ', 'Kirguistan');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('KHM', 'Camboya');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('KIR', 'Kiribati');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('KNA', 'Saint Kitts Y Nevis');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('KOR', 'Corea, Republica De');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('KWT', 'Kuwait');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('LAC', 'America Latina Y El Caribe (Excluido Altos Ingresos)');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('LAO', 'Republica Democratica Popular Lao');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('LBN', 'Libano');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('LBR', 'Liberia');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('LBY', 'Libia');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('LCA', 'Santa Lucia');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('LCN', 'America Latina Y El Caribe');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('LDC', 'Paises Menos Desarrollados: Clasificacion De Las Naciones Unidas');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('LIC', 'Paises De Ingreso Bajo');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('LIE', 'Liechtenstein');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('LKA', 'Sri Lanka');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('LMC', 'Paises De Ingreso Mediano Bajo');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('LMY', 'Ingreso Mediano Y Bajo');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('LSO', 'Lesotho');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('LTE', 'Avanzada Del Dividendo Demografico');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('LTU', 'Lituania');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('LUX', 'Luxemburgo');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('LVA', 'Letonia');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('MAC', 'Region Administrativa Especial De Macao, China');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('MAF', 'Isla De San Martin (Parte Francesa)');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('MAR', 'Marruecos');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('MCO', 'Monaco');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('MDA', 'Republica De Moldova');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('MDG', 'Madagascar');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('MDV', 'Maldivas');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('MEA', 'Oriente Medio Y Norte De Africa');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('MEX', 'Mexico');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('MHL', 'Islas Marshall');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('MIC', 'Ingreso Mediano');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('MKD', 'Macedonia Del Norte');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('MLI', 'Mali');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('MLT', 'Malta');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('MMR', 'Myanmar');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('MNA', 'Oriente Medio Y Norte De Africa (Excluido Altos Ingresos)');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('MNE', 'Montenegro');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('MNG', 'Mongolia');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('MNP', 'Mariana');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('MOZ', 'Mozambique');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('MRT', 'Mauritania');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('MUS', 'Mauricio');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('MWI', 'Malawi');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('MYS', 'Malasia');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('NAC', 'America Del Norte');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('NAM', 'Namibia');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('NCL', 'Nueva Caledonia');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('NER', 'Niger');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('NGA', 'Nigeria');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('NIC', 'Nicaragua');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('NLD', 'Paises Bajos');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('NOR', 'Noruega');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('NPL', 'Nepal');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('NRU', 'Nauru');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('NZL', 'Nueva Zelandia');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('OED', 'Miembros Ocde');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('OMN', 'Oman');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('OSS', 'Otros Estados Pequeos');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('PAK', 'Pakistan');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('PAN', 'Panama');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('PER', 'Peru');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('PHL', 'Filipinas');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('PLW', 'Palau');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('PNG', 'Papua Nueva Guinea');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('POL', 'Polonia');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('PRE', 'Previa Al Dividendo Demografico');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('PRI', 'Puerto Rico');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('PRK', 'Corea, Republica Popular Democratica De');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('PRT', 'Portugal');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('PRY', 'Paraguay');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('PSE', 'Ribera Occidental Y Gaza');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('PSS', 'Estados Pequeos De Las Islas Del Pacfico');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('PST', 'Posterior Al Dividendo Demografico');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('PYF', 'Polinesia Francesa');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('QAT', 'Qatar');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('ROU', 'Rumania');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('RUS', 'Federacion De Rusia');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('RWA', 'Rwanda');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('SAS', 'Asia Meridional');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('SAU', 'Arabia Saudita');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('SDN', 'Sudan');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('SEN', 'Senegal');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('SGP', 'Singapur');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('SLB', 'Islas Salomon');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('SLE', 'Sierra Leona');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('SLV', 'El Salvador');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('SMR', 'San Marino');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('SOM', 'Somalia');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('SRB', 'Serbia');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('SSA', 'Africa Al Sur Del Sahara (Excluido Altos Ingresos)');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('SSD', 'Sudan Del Sur');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('SSF', 'Africa Al Sur Del Sahara');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('SST', 'PequeÃ±os Estados');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('STP', 'Santo Tome Y Principe');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('SUR', 'Suriname');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('SVK', 'Republica Eslovaca');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('SVN', 'Eslovenia');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('SWE', 'Suecia');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('SWZ', 'Eswatini');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('SXM', 'Sint Maarten (Dutch Part)');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('SYC', 'Seychelles');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('SYR', 'Republica Arabe Siria');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('TCA', 'Islas Turcas Y Caicos');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('TCD', 'Chad');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('TEA', 'Asia Oriental Y El Pacifico (Birf Y La Aif)');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('TEC', 'Europa Y Asia Central (Birf Y La Aif)');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('TGO', 'Togo');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('THA', 'Tailandia');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('TJK', 'Tayikistan');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('TKM', 'Turkmenistan');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('TLA', 'America Latina Y El Caribe (Birf Y La Aif)');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('TLS', 'Timor-Leste');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('TMN', 'Oriente Medio Y Norte De Africa (Birf Y La Aif)');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('TON', 'Tonga');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('TSA', 'Asia Meridional (Birf Y La Aif)');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('TSS', 'Africa Al Sur Del Sahara (Birf Y La Aif)');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('TTO', 'Trinidad Y Tobago');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('TUN', 'Tunez');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('TUR', 'Turquia');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('TUV', 'Tuvalu');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('TZA', 'Tanzania');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('UGA', 'Uganda');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('UKR', 'Ucrania');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('UMC', 'Ingreso Mediano Alto');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('URY', 'Uruguay');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('USA', 'Estados Unidos');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('UZB', 'Uzbekistan');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('VCT', 'San Vicente Y Las Granadinas');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('VEN', 'Venezuela');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('VGB', 'Islas Virgenes Britanicas');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('VIR', 'Islas Virgenes (Ee.Uu.)');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('VNM', 'Viet Nam');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('VUT', 'Vanuatu');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('WLD', 'Mundo');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('WSM', 'Samoa');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('XKX', 'Kosovo');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('YEM', 'Yemen, Rep. Del');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('ZAF', 'Sudafrica');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('ZMB', 'Zambia');

INSERT INTO TBL_PAIS (CMP_CODPAIS, CMP_NOMPAIS) 
VALUES ('ZWE', 'Zimbabwe');